### PR TITLE
Add gsplat.js

### PR DESCRIPTION
**Pull request by dylanebert**
yet another one :)

### CODE REVIEW

**Comment by MrNeRF** [comment]
Nice one! Looking forward to see where your project is heading. Promising!

**Comment by AtlasRedux** [comment]
The automatic floater removal option in that one is an absolute godsend!

**Comment by MrNeRF** [comment]
@AtlasRedux Where is it? Could you point me to the code as I did not find it. I would be interested to see how it works. Thx

**Comment by AtlasRedux** [comment]
> @AtlasRedux Where is it? Could you point me to the code as I did not find it. I would be interested to see how it works. Thx

Whops, I was talking about https://github.com/francescofugazzi/3dgsconverter, had my back/forth history on tabs messed up :P

**Pull request merged**
