### PR TITLE
Added WebGPU viewer + visual cleanup in history

### PR DESCRIPTION
**Pull request by MarcusAndreasSvensson**
Hello,

I'd like to contribute the work I've been doing on a viewer built with WebGPU, utilizing the same rasterization techniques as described in the original paper. Please let me know if any modifications should be made to my work to be accepted in this valuable resource!

### CODE REVIEW

**Comment by MrNeRF** [comment]
Wow, really neat. Is think this is the first webgpu-based open sourced one? I will test it out tonight! 
Thx for your contribution!

**Comment by MarcusAndreasSvensson** [comment]
Thank you for the merge!

Well, the [cvlab](https://github.com/cvlab-epfl) implementation is actually also in WebGPU, on which I based my repo. 

They used standard quad rasterization though (same as the webGL viewers) where my main contribution is the compute shader based rasterization and the GPU radix sort that can run on Apple devices.

I mention other works of radix sort in WebGPU in the README as well, but they can't be run on Apple devices unforunately.

**Comment by MrNeRF** [comment]
Nice insights. Do you think you can enhance the linked viewer with this background knowledge you have? I think about a short comment that specifies how these viewers differ or why the one might be more interesting over the other depending on the use case?

**Comment by MarcusAndreasSvensson** [comment]
The most concise way I can think of right now is something like how Dylan does it in his [list](https://huggingface.co/spaces/dylanebert/list-of-splats) Where the cvlab impl. would be quad based and mine would be compute based.

Though I think it would look a bit asymmetrical if we didn't give the same attention to every entry in the list. What do you think?

**Comment by MrNeRF** [comment]
I would like to give a small summary - similar to an abstract but shorter - so people know why it might be worth studying the source code. For sure it should be done for every repo linked. But maybe this is not very practical...

**Comment by MrNeRF** [comment]
Yeah, thats a good idea albeit it should not appear visually cluttered. 
I could advertise this on my twitter profile. I think people are happy to contribute if they can promote their source code and also give a small explanation what makes it special (or what a rather new contribution is)

**Comment by MrNeRF** [comment]
If you like, you could create branch and try it out for the cases you know well?

**Pull request merged**
